# Generated by Django 4.1.4 on 2023-01-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='confirm_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
