# Generated by Django 4.1.4 on 2023-01-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_confirm_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email_verified',
            new_name='is_verified',
        ),
    ]
