# Generated by Django 4.1.4 on 2023-01-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_email_verified_customer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verify_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
